export const RegisterText = {
    text1 : "Sign Up",
    text2 : "Full-Name",
    text3 : "person icon",
    text4 : "Email",
    text5 : "mail icon",
    text6 : "Phone-Number",
    text7 : "phone icon",
    text8 : "Password",
    text9 : "pass icon",
    text10 : "Confirm-Password",
    text11 : "confirm pass icon",
    text12 : "Authorization",
    text13 : "authorization icon",
    text14 : "Submit",
    text15 : "Already have an account?",
    text16 : "Sign in",
    text17 : "full name ",
    text18 : "email",
    text19 : "phone number",
    text20 : "password",
    text21 : "confirm password",
    text22 : "authorization",
}